(()=>{
  const cfg=window.SUPABASE_CONFIG||{};
  const ready=!!(window.supabase&&cfg.url&&!String(cfg.url).includes('COLE_AQUI')&&cfg.key&&!String(cfg.key).includes('COLE_AQUI'));
  const sb=ready?window.supabase.createClient(cfg.url,cfg.key):null;
  const S={route:'home',category:'Geral',mode:'1v1',questions:[],questionIndex:0,matchId:null,match:null,myScore:0,seconds:10,timeLimit:10,timer:null,answered:false,waiting:false,user:null,profile:null,isAdmin:false,realtime:null,poll:null,fiftyUsed:false,plusUsed:false};
  const CATS=[['Geral','🌐','c1'],['Ciência','⚗','c2'],['Entretenimento','🎬','c3'],['Esportes','⚽','c4'],['História','🏛','c5'],['Geografia','📍','c6']];
  const DEMO=[
    ['Qual é o maior planeta do Sistema Solar?',['Terra','Marte','Júpiter','Saturno'],2],['Qual é a capital do Brasil?',['Rio de Janeiro','Brasília','São Paulo','Salvador'],1],['Qual planeta é conhecido como Planeta Vermelho?',['Vênus','Marte','Júpiter','Mercúrio'],1],['Qual gás é essencial para a respiração humana?',['Oxigênio','Hélio','Hidrogênio','Neônio'],0],['Qual personagem usa um martelo chamado Mjolnir?',['Batman','Thor','Hulk','Flash'],1],['Quantos jogadores um time de futebol começa em campo?',['9','10','11','12'],2],['Em que ano o Brasil declarou independência?',['1500','1822','1889','1922'],1],['Qual é o maior país do mundo em área?',['China','Canadá','Rússia','Brasil'],2],['Qual é o satélite natural da Terra?',['Marte','Sol','Lua','Vênus'],2],['Qual instrumento mede a temperatura?',['Barômetro','Termômetro','Higrômetro','Altímetro'],1]
  ];
  const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  function av(v='J',c='avatar'){return `<div class="${c}">${esc(v).slice(0,1).toUpperCase()}</div>`}
  function go(r){clearInterval(S.timer);clearInterval(S.poll);S.route=r;render()}
  function top(){return `<div class="top"><div class="logo"><span class="bolt">ϟ</span>QuizUp</div><div class="top-actions">${S.user?`${S.isAdmin?'<button class="circle" id="adminBtn">⚙</button>':''}<button class="circle" id="logout">↪</button>${av(S.profile?.display_name||'J')}`:''}</div></div>`}
  function bottom(){if(['game','match','result','login','signup','admin'].includes(S.route))return '';return `<nav class="bottom"><button data-r="home">⌂<small>Início</small></button><button data-r="categories">▷<small>Jogar</small></button><button data-r="ranking">♜<small>Ranking</small></button><button data-r="profile">♙<small>Perfil</small></button></nav>`}
  function render(){clearInterval(S.timer);document.getElementById('app').innerHTML=`<div class="app">${top()}${view()}</div>${bottom()}`;bind();nav()}
  function nav(){$$('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.r===S.route))}
  function view(){if(!S.user&&!['login','signup'].includes(S.route))return login();if(S.route==='login')return login();if(S.route==='signup')return signup();if(S.route==='home')return home();if(S.route==='categories')return categories();if(S.route==='match')return match();if(S.route==='game')return game();if(S.route==='result')return result();if(S.route==='ranking')return rank();if(S.route==='profile')return profile();if(S.route==='friends')return friends();if(S.route==='admin')return admin();return achievements()}
  function login(){return `<div class="card pad" style="margin-top:35px;text-align:center"><div class="bolt" style="margin:auto;width:60px;height:60px;font-size:34px">ϟ</div><h1>Entrar no QuizUp</h1><p class="subtitle">Entre na sua conta para jogar partidas online em tempo real.</p><form id="loginForm" class="form" style="text-align:left;margin-top:20px"><label>E-mail</label><input id="email" type="email" required placeholder="seu@email.com"><label>Senha</label><input id="password" type="password" required placeholder="••••••••"><button class="primary">ENTRAR</button></form><button class="secondary" id="signupGo">CRIAR CONTA</button>${!ready?'<div class="notice" style="margin-top:12px">Modo demonstração ativo. Configure <b>config.js</b> para usar contas e partidas reais.</div>':''}</div>`}
  function signup(){return `<div class="card pad" style="margin-top:25px"><div class="title">Criar conta</div><div class="subtitle">Seu nome de jogador será usado no ranking e para encontrar amigos.</div><form id="signupForm" class="form" style="margin-top:18px"><label>Nome de jogador</label><input id="display" required minlength="3" maxlength="20" placeholder="Ex.: Jogador123"><label>E-mail</label><input id="email" type="email" required><label>Senha</label><input id="password" type="password" required minlength="6"><button class="primary">CRIAR CONTA</button></form><button class="secondary" id="loginGo">JÁ TENHO CONTA</button></div>`}
  function home(){const p=S.profile||{};return `<div class="card pad"><div style="display:flex;gap:12px;align-items:center">${av(p.display_name||'J','avatar big')}<div style="flex:1"><b>${esc(p.display_name||'Jogador')}</b><div class="muted">Nível ${p.level||1}</div><div class="xp"><i style="width:${Math.min(100,((p.xp||0)%1000)/10)}%"></i></div><div class="muted">XP ${p.xp||0}</div></div></div><div class="stats"><div class="stat"><b>${p.wins||0}</b><small>VITÓRIAS</small></div><div class="stat"><b>${p.losses||0}</b><small>DERROTAS</small></div><div class="stat"><b>${p.streak||0} 🔥</b><small>SEQUÊNCIA</small></div></div></div><button class="primary" id="play">JOGAR<br><span style="color:#fff">Encontrar adversário</span></button><div class="quick"><button data-go="categories">▤ CATEGORIAS</button><button data-go="ranking">♜ RANKING</button><button data-go="achievements">★ CONQUISTAS</button><button data-go="friends">👥 AMIGOS</button></div><div class="card pad" style="margin-top:12px"><b>Dupla 2x2</b><p class="subtitle">Entre com 3 jogadores aleatórios e a partida divide os 4 em duas equipes.</p><button class="secondary" id="teamPlay">JOGAR 2x2</button></div>`}
  function categories(){return `<div class="title">Escolha uma categoria</div><div class="subtitle">Partidas reais usam as perguntas cadastradas no Supabase.</div><div class="grid">${CATS.map(c=>`<button class="cat ${c[2]}" data-cat="${c[0]}"><span style="font-size:28px">${c[1]}</span><b>${c[0]}</b><small>Escolher categoria</small></button>`).join('')}</div>`}
  function match(){setTimeout(()=>findMatch(),150);return `<div class="card search"><div class="muted">${S.mode==='2v2'?'2x2':'1x1'} • ${esc(S.category)}</div><div class="rings"><div class="big">ϟ</div></div><h2>Procurando adversário…</h2><div class="muted">A fila é sincronizada pelo Supabase.</div><div class="op">${av(S.profile?.display_name||'V','avatar')}<div><b>Você está na fila</b><br><span class="muted">Aguardando ${S.mode==='2v2'?'mais 3 jogadores':'um rival'}</span></div></div><button class="secondary" id="cancel">CANCELAR</button></div>`}
  async function findMatch(){
    if(!sb){S.questions=DEMO.slice();S.matchId='demo';S.match={id:'demo',mode:S.mode,category:S.category,player_ids:[S.user.id,'rival'],team_a:[S.user.id],team_b:['rival'],scores:{[S.user.id]:0,rival:0},current_question:0,state:{question_started_at:Date.now()/1000},status:'playing'};S.questionIndex=0;S.route='game';render();startClock();return;}
    clearInterval(S.poll);
    const attempt=async()=>{
      const {data,error}=await sb.rpc('find_or_create_match',{p_mode:S.mode,p_category:S.category});
      if(error){alert(error.message);return go('categories')}
      if(data){await openMatch(data);return}
      S.poll=setTimeout(attempt,1400);
    };
    attempt();
  }
  async function openMatch(id){
    clearInterval(S.poll);S.matchId=id;
    const {data,error}=await sb.from('matches').select('*').eq('id',id).single();
    if(error||!data){alert(error?.message||'Não foi possível abrir a partida.');return go('categories')}
    S.match=data;S.mode=data.mode;S.category=data.category;S.questionIndex=data.current_question||0;S.answered=false;S.waiting=false;await loadMatchQuestions();subscribeMatch();S.route='game';render();startClock();}
  async function loadMatchQuestions(){
    if(!sb||!S.match?.question_ids?.length){S.questions=DEMO.slice();return;}
    const {data,error}=await sb.from('questions').select('id,question_text,options,correct_index,image_url').in('id',S.match.question_ids);
    if(error||!data||data.length<10){alert('Esta partida não possui 10 perguntas válidas.');return go('categories')}
    const map=new Map(data.map(q=>[q.id,q]));S.questions=S.match.question_ids.map(id=>map.get(id)).filter(Boolean);
  }
  function subscribeMatch(){if(!sb||!S.matchId)return; if(S.realtime)sb.removeChannel(S.realtime);S.realtime=sb.channel(`match-${S.matchId}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'matches',filter:`id=eq.${S.matchId}`},async payload=>{await syncMatch(payload.new)}).subscribe();}
  async function syncMatch(m){
    S.match=m;S.mode=m.mode;S.category=m.category;
    const next=m.current_question||0;
    if(m.status==='finished'){clearInterval(S.timer);await finishOnline();return;}
    if(next!==S.questionIndex){S.questionIndex=next;S.answered=false;S.waiting=false;S.fiftyUsed=false;S.plusUsed=false;S.timeLimit=10;render();startClock();return;}
    const key=`${S.user.id}:${next}`;S.answered=!!m.answers?.[key];S.waiting=S.answered;render();if(!S.answered)startClock();
  }
  function getScore(id){return Number(S.match?.scores?.[id]||0)}
  function totalTeam(team){return (team||[]).reduce((n,id)=>n+getScore(id),0)}
  function myTeam(){return (S.match?.team_a||[]).includes(S.user.id)?S.match.team_a:S.match?.team_b||[S.user.id]}
  function game(){
    const q=S.questions[S.questionIndex]||DEMO[S.questionIndex%DEMO.length];
    const mine=getScore(S.user.id);const rivalIds=(S.match?.player_ids||[]).filter(id=>id!==S.user.id);const rival=rivalIds.length===1?getScore(rivalIds[0]):Math.max(totalTeam(S.match?.team_a||[]),totalTeam(S.match?.team_b||[]))-totalTeam(myTeam());
    const progress=S.questionIndex+1;const answerMap=S.match?.answers||{};const myAnswer=answerMap[`${S.user.id}:${S.questionIndex}`];
    return `<div class="duel"><div>${av(S.profile?.display_name||'V','avatar mini')}<b>Você</b><br><strong>${mine}</strong></div><b>VS</b><div>${av('R','avatar mini')}<b>${S.mode==='2v2'?'Equipe rival':'Rival'}</b><br><strong>${rival}</strong></div></div><div class="qmeta"><span>Pergunta ${progress} / 10</span><div class="timer" id="tm">${S.seconds}</div></div><div class="question">${q.image_url?`<img src="${esc(q.image_url)}">`:''}${esc(q.question_text||q[0])}</div><div class="answers">${(q.options||q[1]).map((a,i)=>`<button class="answer ${myAnswer&&Number(myAnswer.answer)===i?'selected':''}" data-a="${i}" ${S.answered?'disabled':''}><b>${'ABCD'[i]}</b>${esc(a)}</button>`).join('')}</div><div class="power"><button id="fifty" ${S.fiftyUsed?'disabled':''}>◈ 50:50</button><button id="plus" ${S.plusUsed?'disabled':''}>◷ +5s</button><button id="skip" ${S.answered?'disabled':''}>⚡ Pular</button></div><div id="pts">${S.waiting?'<div class="notice center">Resposta enviada. Aguardando os outros jogadores…</div>':''}</div>`;
  }
  function startClock(){clearInterval(S.timer);if(S.answered||S.waiting)return;const started=Number(S.match?.state?.question_started_at||Date.now()/1000);const limit=S.timeLimit||10;const tick=()=>{const elapsed=Math.floor(Date.now()/1000-started);S.seconds=Math.max(0,limit-elapsed);const t=$('#tm');if(t)t.textContent=S.seconds;if(S.seconds<=0){clearInterval(S.timer);answer(-1)}};tick();S.timer=setInterval(tick,250)}
  async function answer(i){if(S.answered||S.waiting)return;S.answered=true;clearInterval(S.timer);const seconds=Math.max(0,S.seconds);if(!sb){const q=S.questions[S.questionIndex]||DEMO[S.questionIndex];const ok=i===q[2];if(ok)S.myScore+=seconds;else S.myScore+=0;render();setTimeout(()=>{if(S.questionIndex>=9){S.route='result';render()}else{S.questionIndex++;S.answered=false;S.match.current_question=S.questionIndex;S.match.state={question_started_at:Date.now()/1000};render();startClock()}},500);return;}
    const {data,error}=await sb.rpc('submit_match_answer',{p_match_id:S.matchId,p_question_index:S.questionIndex,p_answer_index:i,p_seconds:seconds});
    if(error){S.answered=false;alert(error.message);startClock();return;}
    if(data?.finished){const {data:m}=await sb.from('matches').select('*').eq('id',S.matchId).single();if(m)await syncMatch(m);return;}
    S.waiting=true;S.match={...S.match,answers:{...(S.match.answers||{}),[`${S.user.id}:${S.questionIndex}`]:{answer:i,score:data?.added||0}}};render();
  }
  async function finishOnline(){
    if(S.route==='result')return;
    const mine=getScore(S.user.id);const teamA=totalTeam(S.match.team_a),teamB=totalTeam(S.match.team_b);const win=S.mode==='2v2'?(S.match.team_a.includes(S.user.id)?teamA>teamB:teamB>teamA):mine>Math.max(...S.match.player_ids.filter(x=>x!==S.user.id).map(getScore),0);
    if(sb){const {data:existing}=await sb.from('game_results').select('id').eq('match_id',S.matchId).eq('user_id',S.user.id).maybeSingle();if(!existing){await sb.from('game_results').insert({user_id:S.user.id,category:S.category,mode:S.mode,score:mine,won:win,match_id:S.matchId});await sb.rpc('apply_game_result',{p_user_id:S.user.id,p_category:S.category,p_score:mine,p_won:win});await loadProfile();}}
    S.myScore=mine;S.route='result';render();
  }
  function result(){const mine=getScore(S.user.id)||S.myScore;const opponents=(S.match?.player_ids||[]).filter(x=>x!==S.user.id);const oppScore=S.mode==='2v2'?(S.match?.team_a||[]).includes(S.user.id)?totalTeam(S.match.team_b):totalTeam(S.match.team_a):(opponents[0]?getScore(opponents[0]):0);const win=S.mode==='2v2'?mine>oppScore:mine>oppScore;return `<div class="result"><div class="trophy">${win?'🏆':'💥'}</div><div class="winner">${win?'VOCÊ VENCEU!':'QUASE!'}</div><div class="card board"><div>${av(S.profile?.display_name||'J','avatar big')}<div>Você${S.mode==='2v2'?' • sua equipe':''}</div><b class="green">${mine}</b></div><b>VS</b><div>${av('R','avatar big')}<div>${S.mode==='2v2'?'Equipe rival':'Rival'}</div><b class="red">${oppScore}</b></div></div><h2 class="green">+${mine} XP</h2><div class="muted">${win?'+1 vitória':'Continue jogando para subir no ranking'}</div><button class="primary" id="again">JOGAR NOVAMENTE</button><button class="secondary" id="home">VOLTAR AO INÍCIO</button></div>`}
  async function rank(){
    let rows=[];
    if(sb){const {data}=await sb.from('profiles').select('id,display_name,xp,wins').order('xp',{ascending:false}).limit(50);rows=data||[]}
    else rows=[{display_name:'Gabriel',xp:12560},{display_name:'Amanda',xp:11420},{display_name:'Lucas',xp:10870},{display_name:'Maria',xp:9850},{display_name:'Pedro',xp:9120},{id:'demo',display_name:S.profile?.display_name||'Jogador',xp:S.profile?.xp||0}];
    return `<div class="title">Ranking Global</div><div class="tabs"><button class="active">Global</button><button>Semanal</button><button>Amigos</button></div><div class="list">${rows.map((r,i)=>`<div class="row"><b>#${i+1}</b>${av(r.display_name||'J','avatar mini')}<div style="flex:1"><b>${esc(r.display_name)}</b><div class="muted">${r.wins||0} vitórias</div></div><strong>${r.xp||0} XP</strong></div>`).join('')}</div>`}
  function profile(){const p=S.profile||{};return `<div class="title">Meu Perfil</div><div class="card pad center">${av(p.display_name||'J','avatar big')}<h2>${esc(p.display_name||'Jogador')}</h2><div class="muted">Nível ${p.level||1} • ${p.xp||0} XP</div><div class="stats"><div class="stat"><b>${p.wins||0}</b><small>VITÓRIAS</small></div><div class="stat"><b>${p.losses||0}</b><small>DERROTAS</small></div><div class="stat"><b>${p.streak||0}</b><small>SEQUÊNCIA</small></div></div></div><button class="secondary" id="friendsBtn">👥 MEUS AMIGOS</button>`}
  async function friends(){let list=[];if(sb){const {data}=await sb.from('friendships').select('id,requester_id,addressee_id,status').or(`requester_id.eq.${S.user.id},addressee_id.eq.${S.user.id}`).order('created_at',{ascending:false});list=data||[]}return `<div class="title">Amigos</div><form id="friendSearch" class="searchbar"><input id="friendName" placeholder="Procurar por nome"><button>ADICIONAR</button></form><div class="card pad">${list.length?list.map(f=>`<div class="row"><div style="flex:1"><b>${f.status==='accepted'?'Amigo':'Solicitação pendente'}</b><div class="muted">${f.status}</div></div>${f.status==='pending'&&f.addressee_id===S.user.id?`<button class="secondary acceptFriend" data-id="${f.id}">ACEITAR</button>`:''}</div>`).join(''):'<div class="muted">Você ainda não tem amizades.</div>'}</div>`}
  function achievements(){return `<div class="title">Conquistas</div><div class="list"><div class="row"><b>🏆</b><div style="flex:1"><b>Primeira Vitória</b><div class="muted">Vença sua primeira partida</div></div></div><div class="row"><b>🔥</b><div style="flex:1"><b>Sequência de 3</b><div class="muted">Vença 3 partidas seguidas</div></div></div><div class="row"><b>⚡</b><div style="flex:1"><b>Rápido no Gatilho</b><div class="muted">Responda perguntas rapidamente</div></div></div></div>`}
  function admin(){if(!S.isAdmin)return `<div class="card pad"><h2>Acesso negado</h2></div>`;return `<div class="title">Painel do Administrador</div><div class="card pad"><b>Nova categoria</b><form id="catForm" class="form"><input id="catName" placeholder="Nome da categoria" required><input id="catIcon" placeholder="Ícone, ex.: ⚽"><button class="primary">CRIAR CATEGORIA</button></form></div><div class="card pad" style="margin-top:12px"><b>Nova pergunta</b><form id="qForm" class="form"><select id="qCat" required>${CATS.map(c=>`<option>${c[0]}</option>`).join('')}</select><textarea id="qText" required placeholder="Digite a pergunta"></textarea><input id="q0" required placeholder="Alternativa A"><input id="q1" required placeholder="Alternativa B"><input id="q2" required placeholder="Alternativa C"><input id="q3" required placeholder="Alternativa D"><select id="qCorrect"><option value="0">A é correta</option><option value="1">B é correta</option><option value="2">C é correta</option><option value="3">D é correta</option></select><input id="qImage" type="url" placeholder="URL da imagem (opcional)"><button class="primary">SALVAR PERGUNTA</button></form></div>`}
  async function loadProfile(){if(!sb||!S.user)return;const {data}=await sb.from('profiles').select('*').eq('id',S.user.id).single();S.profile=data||{display_name:S.user.email?.split('@')[0]};S.isAdmin=S.profile.role==='admin'}
  async function searchFriend(name){if(!sb||!name)return;const {data,error}=await sb.from('profiles').select('id,display_name').ilike('display_name',`%${name}%`).neq('id',S.user.id).limit(5);if(error)return alert(error.message);if(!data?.length)return alert('Nenhum jogador encontrado.');const target=data[0];const {error:e}=await sb.from('friendships').insert({requester_id:S.user.id,addressee_id:target.id,status:'pending'});if(e)alert(e.message);else{alert(`Solicitação enviada para ${target.display_name}.`);go('friends')}}
  async function acceptFriend(id){const {error}=await sb.from('friendships').update({status:'accepted'}).eq('id',id).eq('addressee_id',S.user.id);if(error)alert(error.message);else go('friends')}
  async function bindAdmin(){if(!sb)return;$('#catForm')?.addEventListener('submit',async e=>{e.preventDefault();const {error}=await sb.from('categories').insert({name:$('#catName').value.trim(),icon:$('#catIcon').value.trim()||'🌐'});if(error)alert(error.message);else{alert('Categoria criada.');render()}});$('#qForm')?.addEventListener('submit',async e=>{e.preventDefault();const options=[$('#q0').value,$('#q1').value,$('#q2').value,$('#q3').value];const {error}=await sb.from('questions').insert({category_name:$('#qCat').value,question_text:$('#qText').value.trim(),options,correct_index:+$('#qCorrect').value,image_url:$('#qImage').value.trim()||null,created_by:S.user.id});if(error)alert(error.message);else{alert('Pergunta salva.');render()}})}
  function bind(){
    $$('.bottom button').forEach(b=>b.onclick=()=>go(b.dataset.r));
    $$('.quick button').forEach(b=>b.onclick=()=>go(b.dataset.go));
    $('#signupGo')?.addEventListener('click',()=>go('signup'));$('#loginGo')?.addEventListener('click',()=>go('login'));
    $('#loginForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!sb)return;const {error}=await sb.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)alert(error.message)});
    $('#signupForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!sb)return;const {error}=await sb.auth.signUp({email:$('#email').value,password:$('#password').value,options:{data:{display_name:$('#display').value.trim()}}});if(error)alert(error.message);else alert('Conta criada. Verifique o e-mail se a confirmação estiver ativada no Supabase.');});
    $('#logout')?.addEventListener('click',async()=>{if(sb)await sb.auth.signOut();S.user=null;S.profile=null;go('login')});
    $('#play')?.addEventListener('click',()=>{S.mode='1v1';go('categories')});$('#teamPlay')?.addEventListener('click',()=>{S.mode='2v2';go('categories')});
    $$('.cat').forEach(b=>b.onclick=()=>{S.category=b.dataset.cat;go('match')});
    $('#cancel')?.addEventListener('click',async()=>{if(sb)await sb.rpc('cancel_match_queue');go('categories')});
    $$('.answer').forEach(b=>b.onclick=()=>answer(+b.dataset.a));$('#plus')?.addEventListener('click',()=>{if(!S.plusUsed&&!S.answered){S.plusUsed=true;S.timeLimit=Math.min(15,(S.timeLimit||10)+5);S.seconds=Math.max(0,S.timeLimit-Math.floor(Date.now()/1000-Number(S.match?.state?.question_started_at||Date.now()/1000)));$('#tm').textContent=S.seconds}});
    $('#fifty')?.addEventListener('click',()=>{if(S.fiftyUsed||S.answered)return;S.fiftyUsed=true;const q=S.questions[S.questionIndex]||DEMO[0];const correct=q.correct_index??q[2];[0,1,2,3].filter(i=>i!==correct).sort(()=>Math.random()-.5).slice(0,2).forEach(i=>document.querySelector(`[data-a="${i}"]`)?.classList.add('dim'))});
    $('#skip')?.addEventListener('click',()=>answer(-1));$('#again')?.addEventListener('click',()=>go('categories'));$('#home')?.addEventListener('click',()=>go('home'));$('#friendsBtn')?.addEventListener('click',()=>go('friends'));$('#adminBtn')?.addEventListener('click',()=>go('admin'));
    $('#friendSearch')?.addEventListener('submit',e=>{e.preventDefault();searchFriend($('#friendName').value.trim())});$$('.acceptFriend').forEach(b=>b.onclick=()=>acceptFriend(b.dataset.id));
    if(S.route==='admin')bindAdmin();
  }
  async function init(){if(!sb){S.user={id:'demo'};S.profile={display_name:'Jogador',level:1,xp:0,wins:0,losses:0,streak:0};render();return;}const {data:{user}}=await sb.auth.getUser();S.user=user||null;if(!S.user)return go('login');await loadProfile();go('home')}
  if(sb){sb.auth.getSession().then(init);sb.auth.onAuthStateChange(()=>setTimeout(init,0))}else init();
})();
