// COLOQUE A URL E A PUBLISHABLE KEY DO SEU PROJETO SUPABASE AQUI.
// Nunca use service_role/secret key no navegador.
window.SUPABASE_CONFIG={url:"COLE_AQUI_SUA_SUPABASE_URL",key:"COLE_AQUI_SUA_SUPABASE_PUBLISHABLE_KEY"};
