-- QuizUp v36.2.7 - migration consolidada Mercado Pago + Coins + segurança
-- Execute depois das migrations anteriores. Não apaga dados existentes.

-- 1. Segurança de cadastro
create unique index if not exists profiles_username_lower_unique on public.profiles(lower(username)) where username is not null;
create or replace function public.is_username_available(p_username text) returns boolean language sql security definer set search_path=public as $$ select not exists(select 1 from public.profiles where lower(username)=lower(trim(p_username))); $$;
revoke all on function public.is_username_available(text) from public; grant execute on function public.is_username_available(text) to anon,authenticated;

-- 2. Controle de pagamentos
alter table public.premium_store_settings add column if not exists payments_enabled boolean not null default false;

-- 3. Pacotes de Coins
create table if not exists public.coin_packages(id uuid primary key default gen_random_uuid(),name text not null,coins bigint not null check(coins>0),price_cents integer not null check(price_cents>0),active boolean not null default true,sort_order integer not null default 0,created_at timestamptz not null default now(),created_by uuid references public.profiles(id) on delete set null);
alter table public.coin_packages enable row level security;
drop policy if exists "coin packages read active" on public.coin_packages;
create policy "coin packages read active" on public.coin_packages for select to authenticated using(active=true or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
drop policy if exists "coin packages admin insert" on public.coin_packages;
create policy "coin packages admin insert" on public.coin_packages for insert to authenticated with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
drop policy if exists "coin packages admin update" on public.coin_packages;
create policy "coin packages admin update" on public.coin_packages for update to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')) with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

insert into public.coin_packages(name,coins,price_cents,sort_order,active) select v.name,v.coins,v.price_cents,v.sort_order,true from (values('Pacote 1.000 Coins',1000,1000,1),('Pacote 2.500 Coins',2500,2000,2),('Pacote 6.000 Coins',6000,4500,3)) v(name,coins,price_cents,sort_order) where not exists(select 1 from public.coin_packages cp where cp.coins=v.coins and cp.price_cents=v.price_cents);

-- 4. Pedidos reais de Coins
create table if not exists public.coin_orders(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,package_id uuid references public.coin_packages(id) on delete set null,coins bigint not null check(coins>0),amount_cents integer not null check(amount_cents>0),status text not null default 'pending' check(status in ('pending','approved','paid','rejected','cancelled','refunded')),provider text not null default 'mercadopago',provider_preference_id text,provider_payment_id text,external_reference text not null unique,raw_payment jsonb,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),paid_at timestamptz);
create unique index if not exists coin_orders_provider_payment_uidx on public.coin_orders(provider,provider_payment_id) where provider_payment_id is not null;
create index if not exists coin_orders_user_created_idx on public.coin_orders(user_id,created_at desc);
create index if not exists coin_orders_status_idx on public.coin_orders(status,created_at desc);
alter table public.coin_orders enable row level security;
drop policy if exists "coin orders own read" on public.coin_orders;
create policy "coin orders own read" on public.coin_orders for select to authenticated using(user_id=auth.uid());
drop policy if exists "coin orders admin read" on public.coin_orders;
create policy "coin orders admin read" on public.coin_orders for select to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- 5. Ledger idempotente
create table if not exists public.coin_ledger(id bigint generated by default as identity primary key,user_id uuid not null references public.profiles(id) on delete cascade,amount bigint not null,source_type text not null,source_id text not null,description text,created_at timestamptz not null default now(),unique(source_type,source_id,user_id));
alter table public.coin_ledger enable row level security;
drop policy if exists "coin ledger own read" on public.coin_ledger;
create policy "coin ledger own read" on public.coin_ledger for select to authenticated using(user_id=auth.uid());

-- 6. Pedido criado no servidor. O cliente não envia preço.
create or replace function public.create_coin_order(p_package_id uuid) returns public.coin_orders language plpgsql security definer set search_path=public as $$
declare p public.coin_packages; s public.premium_store_settings; o public.coin_orders; ref text;
begin
 if auth.uid() is null then raise exception 'Não autenticado'; end if;
 if (select count(*) from public.coin_orders where user_id=auth.uid() and status='pending' and created_at>now()-interval '10 minutes') >= 5 then raise exception 'Muitas compras pendentes. Aguarde alguns minutos antes de criar outra.'; end if;
 select * into s from public.premium_store_settings where id=1;
 if coalesce(s.enabled,false)=false or coalesce(s.coins_enabled,false)=false or coalesce(s.payments_enabled,false)=false then raise exception 'A compra de QuizCoins está desativada'; end if;
 select * into p from public.coin_packages where id=p_package_id and active=true;
 if p.id is null then raise exception 'Pacote de Coins não encontrado ou inativo'; end if;
 o.id:=gen_random_uuid(); ref:='quizup_'||replace(o.id::text,'-','');
 insert into public.coin_orders(id,user_id,package_id,coins,amount_cents,status,external_reference) values(o.id,auth.uid(),p.id,p.coins,p.price_cents,'pending',ref) returning * into o;
 return o;
end $$;
revoke all on function public.create_coin_order(uuid) from public; grant execute on function public.create_coin_order(uuid) to authenticated;

-- 7. Confirmação server-side e crédito atômico. Somente service_role pode executar.
create or replace function public.finalize_coin_payment(p_order_id uuid,p_payment_id text,p_status text,p_amount_cents integer,p_raw jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path=public as $$
declare o public.coin_orders; bal bigint; final_status text;
begin
 select * into o from public.coin_orders where id=p_order_id for update;
 if o.id is null then raise exception 'Pedido não encontrado'; end if;
 final_status:=case when p_status='approved' then 'approved' when p_status in ('pending','in_process','authorized') then 'pending' when p_status in ('cancelled','refunded','charged_back') then 'refunded' else 'rejected' end;
 if o.status in ('approved','paid') then return jsonb_build_object('ok',true,'already_processed',true,'status',o.status,'coins',o.coins); end if;
 if final_status='approved' then
   if p_amount_cents<>o.amount_cents then raise exception 'Valor do pagamento não corresponde ao pedido'; end if;
   if exists(select 1 from public.coin_ledger l where l.source_type='mercadopago_payment' and l.source_id=p_payment_id and l.user_id=o.user_id) then
     update public.coin_orders set status='approved',provider_payment_id=p_payment_id,raw_payment=p_raw,updated_at=now(),paid_at=coalesce(paid_at,now()) where id=o.id;
     return jsonb_build_object('ok',true,'already_processed',true,'status','approved','coins',o.coins);
   end if;
   update public.profiles set coins=coalesce(coins,0)+o.coins where id=o.user_id returning coins into bal;
   insert into public.coin_ledger(user_id,amount,source_type,source_id,description) values(o.user_id,o.coins,'mercadopago_payment',p_payment_id,'Compra de QuizCoins') on conflict do nothing;
   update public.coin_orders set status='approved',provider_payment_id=p_payment_id,raw_payment=p_raw,updated_at=now(),paid_at=now() where id=o.id;
   return jsonb_build_object('ok',true,'already_processed',false,'status','approved','coins',o.coins,'balance',bal);
 end if;
 update public.coin_orders set status=final_status,provider_payment_id=coalesce(provider_payment_id,p_payment_id),raw_payment=p_raw,updated_at=now() where id=o.id;
 return jsonb_build_object('ok',true,'already_processed',false,'status',final_status,'coins',0);
end $$;
revoke all on function public.finalize_coin_payment(uuid,text,text,integer,jsonb) from public; grant execute on function public.finalize_coin_payment(uuid,text,text,integer,jsonb) to service_role;

-- 8. Atualiza preferência pelo usuário autenticado
create or replace function public.set_coin_order_preference(p_order_id uuid,p_preference_id text) returns public.coin_orders language plpgsql security definer set search_path=public as $$
declare o public.coin_orders;
begin update public.coin_orders set provider_preference_id=p_preference_id,updated_at=now() where id=p_order_id and user_id=auth.uid() and status='pending' returning * into o; if o.id is null then raise exception 'Pedido não encontrado'; end if; return o; end $$;
revoke all on function public.set_coin_order_preference(uuid,text) from public; grant execute on function public.set_coin_order_preference(uuid,text) to authenticated;

-- 9. Administração de vendas/contas
create or replace function public.admin_list_coin_orders(p_limit integer default 100) returns table(id uuid,username text,email text,coins bigint,amount_cents integer,status text,provider_payment_id text,created_at timestamptz,paid_at timestamptz) language plpgsql security definer set search_path=public,auth as $$
begin if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin') then raise exception 'Acesso negado'; end if; return query select o.id,p.username,u.email,o.coins,o.amount_cents,o.status,o.provider_payment_id,o.created_at,o.paid_at from public.coin_orders o join public.profiles p on p.id=o.user_id join auth.users u on u.id=o.user_id order by o.created_at desc limit greatest(1,least(coalesce(p_limit,100),500)); end $$;
revoke all on function public.admin_list_coin_orders(integer) from public; grant execute on function public.admin_list_coin_orders(integer) to authenticated;
create or replace function public.admin_list_accounts() returns table(id uuid,username text,display_name text,email text,role text,created_at timestamptz) language plpgsql security definer set search_path=public,auth as $$ begin if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin') then raise exception 'Acesso negado'; end if; return query select p.id,p.username,p.display_name,u.email,p.role,u.created_at from public.profiles p join auth.users u on u.id=p.id order by u.created_at desc; end $$;
grant execute on function public.admin_list_accounts() to authenticated;
create or replace function public.admin_set_player_title(p_user_id uuid,p_title text) returns public.profiles language plpgsql security definer set search_path=public as $$ declare p public.profiles; begin if not exists(select 1 from public.profiles a where a.id=auth.uid() and a.role='admin') then raise exception 'Acesso negado'; end if; update public.profiles set premium_title=nullif(trim(p_title),'') where id=p_user_id returning * into p; if p.id is null then raise exception 'Jogador não encontrado'; end if; return p; end $$;
grant execute on function public.admin_set_player_title(uuid,text) to authenticated;

-- 10. Índices úteis
create index if not exists coin_orders_external_ref_idx on public.coin_orders(external_reference);


-- 11. MERCADO PAGO DESATIVADO POR PADRÃO (estrutura permanece pronta)
update public.premium_store_settings set payments_enabled=false where id=1;

-- 12. Coins: crédito manual seguro pelo administrador
create or replace function public.admin_grant_coins(p_username text,p_amount bigint,p_reason text default 'Crédito manual do administrador')
returns jsonb language plpgsql security definer set search_path=public as $$
declare target public.profiles; bal bigint; src text;
begin
  if not exists(select 1 from public.profiles where id=auth.uid() and role='admin') then raise exception 'Acesso negado'; end if;
  if p_amount is null or p_amount <= 0 then raise exception 'Quantidade de Coins inválida'; end if;
  select * into target from public.profiles where lower(username)=lower(trim(p_username)) limit 1;
  if target.id is null then raise exception 'Jogador não encontrado'; end if;
  src:='admin_grant_'||gen_random_uuid()::text;
  update public.profiles set coins=coalesce(coins,0)+p_amount where id=target.id returning coins into bal;
  insert into public.coin_ledger(user_id,amount,source_type,source_id,description)
    values(target.id,p_amount,'admin_grant',src,coalesce(nullif(trim(p_reason),''),'Crédito manual do administrador'));
  return jsonb_build_object('ok',true,'user_id',target.id,'username',target.username,'coins',p_amount,'balance',bal);
end $$;
revoke all on function public.admin_grant_coins(text,bigint,text) from public;
grant execute on function public.admin_grant_coins(text,bigint,text) to authenticated;

-- 13. Suporte / conversa com a equipe
create table if not exists public.support_threads(
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'open' check(status in ('open','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists support_threads_one_per_user on public.support_threads(user_id);
create index if not exists support_threads_updated_idx on public.support_threads(updated_at desc);

create table if not exists public.support_messages(
  id uuid primary key default gen_random_uuid(),
  thread_id uuid not null references public.support_threads(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  message text not null check(length(trim(message)) between 1 and 1000),
  created_at timestamptz not null default now()
);
create index if not exists support_messages_thread_idx on public.support_messages(thread_id,created_at);

alter table public.support_threads enable row level security;
alter table public.support_messages enable row level security;

drop policy if exists "support threads own read" on public.support_threads;
create policy "support threads own read" on public.support_threads for select to authenticated
using(user_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
drop policy if exists "support threads own insert" on public.support_threads;
create policy "support threads own insert" on public.support_threads for insert to authenticated
with check(user_id=auth.uid());
drop policy if exists "support threads admin update" on public.support_threads;
create policy "support threads admin update" on public.support_threads for update to authenticated
using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'))
with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

drop policy if exists "support messages participants read" on public.support_messages;
create policy "support messages participants read" on public.support_messages for select to authenticated
using(
  exists(select 1 from public.support_threads t where t.id=thread_id and
    (t.user_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')))
);
drop policy if exists "support messages participant insert" on public.support_messages;
create policy "support messages participant insert" on public.support_messages for insert to authenticated
with check(
  sender_id=auth.uid() and
  exists(select 1 from public.support_threads t where t.id=thread_id and
    (t.user_id=auth.uid() or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')))
);

-- 14. Sessão única por conta: o último aparelho conectado derruba o anterior
create table if not exists public.quizup_active_sessions(
  user_id uuid primary key references public.profiles(id) on delete cascade,
  session_id text not null,
  last_seen_at timestamptz not null default now()
);
create index if not exists quizup_active_sessions_seen_idx on public.quizup_active_sessions(last_seen_at);

alter table public.quizup_active_sessions enable row level security;
drop policy if exists "quizup sessions own read" on public.quizup_active_sessions;
create policy "quizup sessions own read" on public.quizup_active_sessions for select to authenticated using(user_id=auth.uid());

create or replace function public.claim_quizup_session(p_session_id text)
returns boolean language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null or nullif(trim(p_session_id),'') is null then return false; end if;
  insert into public.quizup_active_sessions(user_id,session_id,last_seen_at)
    values(auth.uid(),trim(p_session_id),now())
  on conflict(user_id) do update set session_id=excluded.session_id,last_seen_at=now();
  return true;
end $$;
create or replace function public.touch_quizup_session(p_session_id text)
returns boolean language sql security definer set search_path=public as $$
  update public.quizup_active_sessions
    set last_seen_at=now()
  where user_id=auth.uid() and session_id=trim(p_session_id)
  returning true;
$$;
create or replace function public.release_quizup_session(p_session_id text)
returns boolean language sql security definer set search_path=public as $$
  delete from public.quizup_active_sessions where user_id=auth.uid() and session_id=trim(p_session_id)
  returning true;
$$;
revoke all on function public.claim_quizup_session(text) from public;
revoke all on function public.touch_quizup_session(text) from public;
revoke all on function public.release_quizup_session(text) from public;
grant execute on function public.claim_quizup_session(text) to authenticated;
grant execute on function public.touch_quizup_session(text) to authenticated;
grant execute on function public.release_quizup_session(text) to authenticated;

-- 15. Reações: índice e proteção contra spam/duplicação
create index if not exists match_reactions_match_created_idx on public.match_reactions(match_id,created_at desc);
