-- QuizUp v36.2.2 - MIGRAÇÃO CONSOLIDADA
-- Execute ESTE arquivo no Supabase. Ele inclui as tabelas premium que a v36.2.1 usava
-- antes de alterar colunas, evitando: relation public.premium_items does not exist.

-- Perfil / VIP / cosméticos ativos
alter table public.profiles add column if not exists draws integer not null default 0;
alter table public.profiles add column if not exists premium_vip boolean not null default false;
alter table public.profiles add column if not exists premium_title text;
alter table public.profiles add column if not exists premium_frame text;
alter table public.profiles add column if not exists premium_effect text;
alter table public.profiles add column if not exists premium_theme text;
alter table public.profiles add column if not exists premium_avatar text;
alter table public.profiles add column if not exists premium_badge text;

-- Catálogo premium: cria antes de qualquer ALTER/REFERÊNCIA.
create table if not exists public.premium_items (
  id text primary key,
  name text not null,
  category text not null,
  description text,
  price_cents integer not null default 0,
  icon text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.premium_items add column if not exists asset_url text;
alter table public.premium_items add column if not exists kind text;
alter table public.premium_items add column if not exists created_by uuid references public.profiles(id) on delete set null;

-- Inventário do usuário.
create table if not exists public.user_premium_items (
  user_id uuid not null references public.profiles(id) on delete cascade,
  item_id text not null references public.premium_items(id) on delete cascade,
  active boolean not null default false,
  purchased_at timestamptz not null default now(),
  primary key(user_id,item_id)
);

-- Pedidos/pagamentos.
create table if not exists public.premium_orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  item_id text references public.premium_items(id),
  amount_cents integer not null,
  provider text,
  provider_payment_id text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

-- Catálogo inicial (idempotente).
insert into public.premium_items(id,name,category,description,price_cents,icon) values
('frame-vip','Moldura VIP','Molduras','Brilho dourado exclusivo no avatar.',490,'👑'),
('frame-diamond','Moldura Diamante','Molduras','Efeito cristalino de destaque.',990,'💎'),
('frame-galaxy','Moldura Galáxia','Molduras','Visual lendário com brilho cósmico.',1490,'🌌'),
('effect-electric','Vitória Elétrica','Efeitos','Animação especial ao vencer.',490,'⚡'),
('effect-fire','Vitória em Chamas','Efeitos','Explosão visual de fogo na vitória.',790,'🔥'),
('effect-diamond','Vitória Diamante','Efeitos','Efeito raro de cristal.',990,'💎'),
('title-genius','GÊNIO','Títulos','Mostre seu estilo nas partidas.',290,'🧠'),
('title-master','MESTRE','Títulos','Título especial para seu perfil.',390,'🏆'),
('title-legend','LENDÁRIO','Títulos','Status raro e chamativo.',690,'👑'),
('emoji-troll','Pacote Troll','Emojis','Reações premium para duelos.',390,'😈'),
('emoji-elite','Pacote Elite','Emojis','Reações premium para duelos.',490,'😎'),
('avatar-ninja','Avatar Ninja','Avatares','Avatar exclusivo.',590,'🥷'),
('theme-gold','Tema Ouro','Temas','Perfil preto e dourado.',690,'✨'),
('theme-galaxy','Tema Galáxia','Temas','Visual cósmico.',890,'🌌')
on conflict (id) do update set active=true;

-- Empates.
alter table public.game_results add column if not exists outcome text;
update public.game_results set outcome=case when won then 'win' else 'loss' end where outcome is null;
alter table public.game_results drop constraint if exists game_results_outcome_check;
alter table public.game_results add constraint game_results_outcome_check check (outcome in ('win','loss','draw'));

-- Reações durante a partida.
create table if not exists public.match_reactions (
  id bigint generated by default as identity primary key,
  match_id uuid not null references public.matches(id) on delete cascade,
  sender_id uuid not null references auth.users(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  constraint match_reactions_emoji_check check (char_length(emoji) between 1 and 8)
);
create index if not exists match_reactions_match_created_idx on public.match_reactions(match_id,created_at);
alter table public.match_reactions enable row level security;
drop policy if exists "match reactions read participants" on public.match_reactions;
create policy "match reactions read participants" on public.match_reactions for select to authenticated using (exists(select 1 from public.matches m where m.id=match_reactions.match_id and auth.uid()=any(m.player_ids)));
drop policy if exists "match reactions insert participants" on public.match_reactions;
create policy "match reactions insert participants" on public.match_reactions for insert to authenticated with check (sender_id=auth.uid() and exists(select 1 from public.matches m where m.id=match_reactions.match_id and auth.uid()=any(m.player_ids)));
do $$ begin alter publication supabase_realtime add table public.match_reactions; exception when duplicate_object then null; end $$;

-- Função: somente um cosmético ativo por categoria.
create or replace function public.activate_premium_item(p_item_id text)
returns public.premium_items
language plpgsql security definer set search_path=public
as $$
declare item public.premium_items;
begin
  select * into item from public.premium_items where id=p_item_id and active=true;
  if item.id is null then raise exception 'Item premium não encontrado'; end if;
  insert into public.user_premium_items(user_id,item_id,active) values(auth.uid(),item.id,true)
  on conflict(user_id,item_id) do update set active=true;
  update public.user_premium_items up set active=false from public.premium_items other
  where up.user_id=auth.uid() and up.item_id=other.id and other.category=item.category and up.item_id<>item.id;
  return item;
end $$;

-- Storage dos itens da loja.
insert into storage.buckets(id,name,public) values('premium-assets','premium-assets',true) on conflict(id) do update set public=true;
drop policy if exists "premium assets public read" on storage.objects;
create policy "premium assets public read" on storage.objects for select to public using(bucket_id='premium-assets');
drop policy if exists "premium assets admin insert" on storage.objects;
create policy "premium assets admin insert" on storage.objects for insert to authenticated with check(bucket_id='premium-assets' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
drop policy if exists "premium assets admin update" on storage.objects;
create policy "premium assets admin update" on storage.objects for update to authenticated using(bucket_id='premium-assets' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')) with check(bucket_id='premium-assets' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
drop policy if exists "premium assets admin delete" on storage.objects;
create policy "premium assets admin delete" on storage.objects for delete to authenticated using(bucket_id='premium-assets' and exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- RLS do catálogo.
alter table public.premium_items enable row level security;
drop policy if exists "premium items read active" on public.premium_items;
create policy "premium items read active" on public.premium_items for select to authenticated using(active=true or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
drop policy if exists "premium items admin insert" on public.premium_items;
create policy "premium items admin insert" on public.premium_items for insert to authenticated with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));
drop policy if exists "premium items admin update" on public.premium_items;
create policy "premium items admin update" on public.premium_items for update to authenticated using(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin')) with check(exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='admin'));

-- RLS básico do inventário/pedidos.
alter table public.user_premium_items enable row level security;
drop policy if exists "users read own premium inventory" on public.user_premium_items;
create policy "users read own premium inventory" on public.user_premium_items for select to authenticated using(user_id=auth.uid());
drop policy if exists "users manage own premium inventory" on public.user_premium_items;
create policy "users manage own premium inventory" on public.user_premium_items for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
